folders:
  - folder_path: "odin"
    description: "odin service jobs"
  - folder_path: "asgard"
    description: "asgard cluster provisioning jobs"
jobs:
  - job_path: "odin/build_job"
    jenkinsfile_git_repo: "https://github.com/yogeshrnaik/odin.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
  - job_path: "asgard/cluster"
    jenkinsfile_git_repo: "https://github.com/yogeshrnaik/asgard-infrastructure.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
  - job_path: "asgard/alb-and-dns"
    jenkinsfile_git_repo: "https://github.com/yogeshrnaik/asgard-infrastructure.git"
    jenkinsfile_path: "exercise3/app-dns-and-alb/alb_dns_pipeline"
    auto_trigger: true